<h3> Get to Know a numpy Array </h3>

You will use the numpy array <code> A</code> for the following 

In [1]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1) type using the function type 

In [2]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])

2) the shape of the array 

In [3]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

3) the type of data in the array 

In [10]:
 A=np.array([[1,2],[3,4],[5,6],[7,8]])

B=np.array([[1,2,3],[4,5,6]])

A




array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

4) Find the second row of the numpy array <code>A</code>:

In [11]:
B

array([[1, 2, 3],
       [4, 5, 6]])

<h3> Two kinds of Multiplying  </h3>

you will use the following numpy arrays for the next questions 

In [8]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) multiply array <code> A </code> and <code>B</code>

In [15]:
np.array[0,0]

TypeError: 'builtin_function_or_method' object is not subscriptable

2)  plot the function

In [14]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)


0

<hr>
<small>Copyright &copy; 2018 IBM Cognitive Class. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license/).</small>