In [5]:
import numpy as np

In [9]:
y=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
x=[1,2,3,4,5]

In [12]:
y


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
x

[1, 2, 3, 4, 5]

In [33]:
x=np.array(x)

In [45]:
y=np.array(y)

In [21]:
np.zeros((3,3)) +5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [26]:
np.ones((3,2))




array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
x.max()

5

In [35]:
np.random.rand(5)

array([0.02623998, 0.60224064, 0.88719792, 0.75386486, 0.52550585])

In [36]:
np.random.randn(5)

array([ 0.3352566 , -1.17140756,  0.61041732,  1.03249216,  0.29435984])

In [37]:
np.random.randint(5)

4

In [46]:
y.arg()

AttributeError: 'numpy.ndarray' object has no attribute 'arg'